### ISSUE TITLE
visualization for the results

### ISSUE THREAD

**Issue by mtli77** [huangjh-pub/multibody-sync#1]
@huangjh-pub 
Hi, thanks for sharing the wonderful work.
Could you please share the visualization scripts and software in the paper?
Best regards.

**Comment by huangjh-pub** [comment]
Hi. Thanks for the question!
The figures are created by first converting points into spheres (using [Open3D](http://www.open3d.org/)) and then rendered with [blender](https://www.blender.org/) cycles.
Best,
the authors

**Comment by ANABUR920** [comment]
Could you share more detail about how to render it via blender?
