### ISSUE TITLE
CPU not supported

### ISSUE THREAD

**Issue by saru-d2** [huangjh-pub/multibody-sync#3]
Hi, 

first off, big fan of your work!

I'm running into this issue on both google Colab and a laptop equipped with an intel 6700HQ.

```
RuntimeError: CPU not supported
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_7934/2228935556.py in <module>
      1 import numpy as np
      2 data = np.expand_dims(np.load('assets/laptop.npy'), axis=0)
----> 3 my_model.forward(torch.from_numpy(data))

~/saru/multibody-sync/test.py in forward(self, xyz)
    172         # Sub-Sample for motion synchronization.
    173         xyz_gathered = xyz.reshape(n_batch * n_view, n_point, 3).contiguous()
--> 174         sub_inds = pointnet2_util.furthest_point_sample(xyz_gathered, self.nsample_motion).long()
    175         xyz_down = pointnet2_util.gather_nd(xyz_gathered, sub_inds)
    176         sub_inds = break_leading_dim([n_batch, n_view], sub_inds)

~/saru/multibody-sync/utils/pointnet2_util.py in forward(ctx, xyz, npoint)
     11     @staticmethod
     12     def forward(ctx, xyz, npoint):
---> 13         return _ext.furthest_point_sampling(xyz, npoint)
     14 
     15     @staticmethod

RuntimeError: CPU not supported
```

Any help would be appreciated!

Thanks, Saru

**Comment by heiwang1997** [comment]
Hi @saru-d2, thank you so much for your interest in our work!

Unfortunately, the code currently does not support CPU. You can either switch to a workstation with a GPU or turn on the GPU acceleration in google colab as instructed [here](https://colab.research.google.com/notebooks/gpu.ipynb).

Hope that helps!

**Comment by saru-d2** [comment]
Hi @heiwang1997 ,

The laptop I'm using is equipped with a gtx 1060 and I used colab, which at the time was allocated a tesla k80.
 You can find the notebook I tried on colab [here](https://colab.research.google.com/drive/1papP7ED099m-ZNqe9xLAF0Xj2fmWUfFW?usp=sharing) .

Thanks, Saru

**Comment by heiwang1997** [comment]
Hi, could you please quickly try:

    my_model.forward(torch.from_numpy(data).float().cuda())

in your colab please?

**Comment by saru-d2** [comment]
Hi, 

I'm getting a CUDA out of memory error, on both my local machine and on colab. but the CPU not supported error is gone.

Should I be using better hardware?

Thanks, Saru

**Comment by heiwang1997** [comment]
Hi Saru,

I got where the problem was. You can add `with torch.no_grad()` before the inference so no gradient is recorded during test time. It costs ~2GB mem so no need to update your hardware (yay!)

Best,
Jiahui

**Comment by saru-d2** [comment]
This fixed it! Thanks. One more thing, where is the result stored, and how do I visualize it?

Thanks, Saru

**Comment by heiwang1997** [comment]
In Colab I guess the newest [Open3D release](http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html) will allow you to visualize 3D within a browser. You can try setting that up :)
The current code only supports visualization in X11.
