### ISSUE TITLE
metric computation

### ISSUE THREAD

**Issue by ray8828** [huangjh-pub/multibody-sync#4]
Hi, thanks for sharing the interesting work. I'm comparing my method with yours on your two datasets, could you point me to the code that computes the metric, specifically, I'm interested in Flow Accuracy (EPE3D). Could you provide the code for this? Thanks!

**Comment by heiwang1997** [comment]
Sure! The following code provides an example. It forwards the model, takes `full_flow` from the dataset loader, and computes the metric. You can average across the dataset to get the final metric (we multiply the values by 100 in our paper):

    pd_segm, xyz_trans = model(inputs)
    all_epe3d = []
    consis_flow = xyz_trans - inputs
    for view_i in range(4):
        for view_j in range(4):
            if view_i == view_j:
                continue
            gt_f = full_flow[:, view_j + view_i * 4]
            pd_fi0 = consis_flow[:, view_i]
            pd_fj0 = consis_flow[:, view_j]
            d_f = feature_propagation(pd_fi0 + inputs[:, view_i], pd_fj0 + inputs[:, view_j], -pd_fj0, transposed=False)
            pd_f = pd_fi0 + d_f
            epe3d = torch.norm(pd_f - gt_f, dim=-1).mean().item()
            all_epe3d.append(epe3d)
    cur_mean = np.mean(all_epe3d)
    cur_std = np.std(all_epe3d)

**Comment by ray8828** [comment]
Thanks! This really helps!
